name: Run pre-commit checks

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Pipx puts executables here.
      - run: printf "%s/.local/bin\n" "${HOME}" >> "${GITHUB_PATH}"

      - run: python3 -m pip install pipx

      - run: pipx install poetry && pipx list

      - uses: actions/checkout@v3

      - run: poetry install

      - uses: giantswarm/install-binary-action@v1.1.0
        with:
          binary: actionlint
          version: 1.6.25
          download_url: "https://github.com/rhysd/actionlint/releases/download/v1.6.25/actionlint_${version}_linux_amd64.tar.gz"
          tarball_binary_path: "${binary}"
          smoke_test: "${binary} --version"

      - run: poetry run pre-commit run --all-files

      - run: poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  release:
    needs: build
    if: "github.ref_type == 'tag'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
    permissions:
      contents: write

  publish:
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: TestPyPI
    permissions:
      id-token: write
    steps:
      - name: Download package distributions
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
