name: Run pre-commit checks

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install actionlint
        uses: giantswarm/install-binary-action@v1.1.0
        with:
          binary: actionlint
          version: 1.6.25
          download_url: "https://github.com/rhysd/actionlint/releases/download/v${version}/actionlint_${version}_linux_amd64.tar.gz"
          tarball_binary_path: "${binary}"
          smoke_test: "${binary} --version"

      - name: Install project
        run: poetry install

      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files

      - name: Build package distributions
        run: poetry build

      - name: Upload package distributions
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  release:
    needs: build
    if: "github.ref_type == 'tag'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
    permissions:
      contents: write

  publish:
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: TestPyPI
    permissions:
      id-token: write
    steps:
      - name: Download package distributions
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
